name: particle_setup
description: Flutter library to send commands to Particle IoT devices (https://www.particle.io/).
author: Kirk Eaton <kirk.eaton@gmail.com>
homepage: https://github.com/kirkeaton/particle_setup
version: 0.3.0

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  asn1lib: ^0.5.14
  convert: ^2.1.1
  json_annotation: ^3.0.0
  pointycastle: ^1.0.2

  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.2.3

  flutter_test:
    sdk: flutter
