version: 2.1
jobs:
  build_and_test:
    docker:
      - image: google/dart:2.10
    steps:
      - checkout
      - run: pub get
      - run: pub run build_runner build
      - run: pub run build_runner test
workflows:
  default:
    jobs:
      - build_and_test:
          filters:
            branches:
              only: /.*/
